version: '2'
services:
  redis:
    image: redis:redis-5.0.5_cluster-1.0
    build: ./redis
    command: redis-server --cluster-enabled yes --bind 0.0.0.0 --loglevel warning
    ports: 
     - 6379
     - 16379
    labels:
     - redis

  cluster:
    image: docker:18.09.6
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    command: |
      sh -c "
        sleep 2
        cluster_hosts=
        docker ps -q -f label=redis |
        {
          while read x; do
            private_ip=$$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$x)
            cluster_hosts=\"$$cluster_hosts $$private_ip:6379\"
          done
          docker run --rm --network=redis-cluster-docker_default redis:5.0.5-alpine sh -c \"yes 'yes' | redis-cli --cluster create $$cluster_hosts --cluster-replicas 1\"
        }
      "
    depends_on:
     - redis
